{{- if .Values.build.auth.git.username }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-build-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-build-bot
subjects:
- kind: ServiceAccount
  name: knative-build-bot
{{- end }}