apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "build.controller.name" . }}-admin-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "build.name" . }}-admin
subjects:
- kind: ServiceAccount
  name: {{ template "build.controller.name" . }}
  namespace: {{ .Release.Namespace }}
